[book]
title = "Team Rudra Programming"
author = "Team-Rudra-Robocon"
description = "Documentation for programming-related aspects since 2022."

[build]
create-missing = true

[output.html]
default-theme = "dark"
additional-css = ["src/css/custom.css"]  # Add custom styling if needed.

[output.html.fold]
enable = true

